Repository SJ-Plan-B/Plan-Bot, pull requests merged in 2022-07, with the labels that each got.

#91 1.2.3.1
  commands/sendrolereaction.js
  events/interactionCreate.js
  index.js
  information/interaction.json
  package-lock.json
  package.json
Labels: Feature Edit

#93 added First logger functions
  .gitignore
  data/example.logger.json
  index.js
  information/test.js
  logger/channelCreate.js
  logger/channelDelete.js
  util/logger.js
Labels: enhancement, Feature Edit

#99 Coconut
  commands/coconut.js
Labels: Feature Request
